# Generated by Django 3.0.3 on 2020-03-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecard',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='namecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
