# Generated by Django 3.0.3 on 2020-02-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
