# Generated by Django 3.0.3 on 2020-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0002_auto_20200219_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='board',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
